// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cpu_cpu_Pipeline_VITIS_LOOP_101_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mem_address0,
        mem_ce0,
        mem_we0,
        mem_d0,
        mem_q0,
        reg_file_address0,
        reg_file_ce0,
        reg_file_we0,
        reg_file_d0,
        reg_file_q0,
        reg_file_address1,
        reg_file_ce1,
        reg_file_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] mem_address0;
output   mem_ce0;
output   mem_we0;
output  [31:0] mem_d0;
input  [31:0] mem_q0;
output  [4:0] reg_file_address0;
output   reg_file_ce0;
output   reg_file_we0;
output  [31:0] reg_file_d0;
input  [31:0] reg_file_q0;
output  [4:0] reg_file_address1;
output   reg_file_ce1;
input  [31:0] reg_file_q1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [31:0] state_load_load_fu_579_p1;
wire   [6:0] opcode_1_load_fu_557_p1;
wire   [0:0] icmp_ln101_fu_573_p2;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_subdone;
wire   [2:0] grp_fu_436_p3;
reg   [2:0] reg_462;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
reg   [0:0] icmp_ln101_reg_1540;
reg   [31:0] state_load_reg_1544;
reg   [6:0] opcode_1_reg_1528;
reg   [31:0] reg_466;
reg   [2:0] funct3_reg_1595;
reg   [31:0] reg_471;
reg   [4:0] rd_1_reg_1511;
wire    ap_block_pp0_stage1_11001;
reg   [31:0] insn_reg_1519;
reg   [21:0] pc_9_reg_1532;
wire   [0:0] icmp_ln125_fu_586_p2;
reg   [0:0] icmp_ln125_reg_1548;
wire   [0:0] icmp_ln222_fu_680_p2;
reg   [0:0] icmp_ln222_reg_1562;
wire   [31:0] result_16_fu_686_p2;
reg   [31:0] result_16_reg_1566;
wire   [0:0] icmp_ln164_fu_707_p2;
reg   [0:0] icmp_ln164_reg_1581;
wire   [2:0] grp_fu_429_p3;
wire   [12:0] imm_b_fu_749_p6;
reg   [12:0] imm_b_reg_1599;
wire  signed [20:0] imm_j_2_fu_852_p2;
reg  signed [20:0] imm_j_2_reg_1644;
wire   [0:0] icmp_ln55_fu_894_p2;
reg   [0:0] icmp_ln55_reg_1655;
wire   [31:0] result_12_fu_900_p2;
reg   [31:0] result_12_reg_1665;
wire   [31:0] result_13_fu_906_p2;
reg   [31:0] result_13_reg_1670;
wire   [0:0] icmp_ln53_fu_912_p2;
reg   [0:0] icmp_ln53_reg_1675;
wire   [11:0] grp_fu_450_p3;
reg   [11:0] imm_1_reg_1680;
wire   [31:0] result_1_fu_935_p2;
reg   [31:0] result_1_reg_1685;
wire   [31:0] result_3_fu_941_p2;
reg   [31:0] result_3_reg_1690;
wire   [1:0] trunc_ln183_fu_972_p1;
reg   [1:0] trunc_ln183_reg_1700;
wire   [0:0] icmp_ln180_fu_976_p2;
reg   [0:0] icmp_ln180_reg_1705;
wire   [0:0] icmp_ln180_1_fu_982_p2;
reg   [0:0] icmp_ln180_1_reg_1710;
reg   [31:0] word_reg_1715;
wire    ap_block_pp0_stage3_11001;
wire   [7:0] byte_fu_1298_p1;
reg   [7:0] byte_reg_1720;
wire    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln238_fu_627_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln239_fu_632_p1;
wire   [63:0] zext_ln223_fu_692_p1;
wire   [63:0] zext_ln197_fu_697_p1;
wire   [63:0] zext_ln178_fu_702_p1;
wire   [63:0] zext_ln168_fu_713_p1;
wire   [63:0] zext_ln169_fu_718_p1;
wire   [63:0] zext_ln153_fu_763_p1;
wire   [63:0] zext_ln153_1_fu_768_p1;
wire   [63:0] zext_ln149_fu_773_p1;
wire   [63:0] zext_ln149_1_fu_778_p1;
wire   [63:0] zext_ln145_fu_783_p1;
wire   [63:0] zext_ln145_1_fu_788_p1;
wire   [63:0] zext_ln141_fu_793_p1;
wire   [63:0] zext_ln141_1_fu_798_p1;
wire   [63:0] zext_ln126_fu_869_p1;
wire   [63:0] zext_ln105_fu_884_p1;
wire   [63:0] zext_ln228_fu_918_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln182_fu_967_p1;
wire   [63:0] zext_ln169_1_fu_1023_p1;
wire   [63:0] zext_ln242_fu_1155_p1;
wire    ap_block_pp0_stage3;
reg    ap_predicate_pred357_state4;
wire   [63:0] zext_ln212_fu_1262_p1;
reg    ap_predicate_pred363_state4;
wire   [63:0] zext_ln189_fu_1421_p1;
wire    ap_block_pp0_stage0;
reg    ap_predicate_pred374_state5;
reg   [20:0] imm_j_fu_192;
reg    ap_predicate_pred381_state4;
reg   [4:0] rd_fu_196;
wire    ap_loop_init;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] insn_int_fu_200;
reg   [6:0] opcode_fu_204;
wire   [6:0] opcode_2_fu_600_p1;
reg    ap_predicate_pred341_state5;
reg    ap_predicate_pred124_state4;
reg    ap_predicate_pred128_state4;
reg    ap_predicate_pred346_state4;
wire   [0:0] grp_fu_511_p2;
wire   [0:0] grp_fu_517_p2;
reg   [21:0] pc_fu_208;
wire   [21:0] pc_16_fu_1425_p2;
wire   [21:0] grp_fu_457_p2;
wire   [21:0] pc_14_fu_1320_p2;
wire   [21:0] pc_13_fu_1358_p2;
reg    ap_predicate_pred468_state4;
reg    ap_predicate_pred494_state4;
reg   [31:0] state_fu_212;
reg    reg_file_ce1_local;
reg   [4:0] reg_file_address1_local;
reg    reg_file_ce0_local;
reg   [4:0] reg_file_address0_local;
reg    reg_file_we0_local;
reg   [31:0] reg_file_d0_local;
wire   [31:0] result_15_fu_665_p3;
wire   [31:0] zext_ln126_1_fu_864_p1;
wire   [31:0] result_14_fu_1116_p19;
wire   [31:0] result_5_fu_1227_p17;
wire   [31:0] loaded_1_fu_1401_p9;
reg    mem_ce0_local;
reg   [9:0] mem_address0_local;
reg    mem_we0_local;
reg    ap_predicate_pred140_state4;
reg    ap_predicate_pred145_state4;
reg    ap_predicate_pred150_state4;
reg    ap_predicate_pred155_state4;
wire   [14:0] tmp_2_fu_563_p4;
wire   [6:0] trunc_ln119_fu_592_p1;
wire   [4:0] grp_fu_415_p3;
wire   [4:0] grp_fu_422_p3;
wire   [11:0] lower_fu_637_p3;
wire   [31:0] zext_ln218_fu_645_p1;
wire   [31:0] sub_ln219_fu_649_p2;
wire   [19:0] tmp_s_fu_655_p4;
wire   [31:0] zext_ln119_1_fu_582_p1;
wire   [0:0] tmp_9_fu_731_p3;
wire   [5:0] tmp_1_fu_739_p4;
wire   [3:0] tmp_3_fu_723_p3;
wire   [7:0] tmp_fu_806_p3;
wire   [0:0] tmp_8_fu_814_p3;
wire   [9:0] tmp_4_fu_822_p3;
wire   [18:0] tmp_6_fu_830_p4;
wire   [20:0] imm_j_1_fu_840_p5;
wire   [7:0] zext_ln119_fu_596_p1;
wire   [7:0] add_ln126_fu_858_p2;
wire   [4:0] lshr_ln_fu_874_p4;
wire   [6:0] grp_fu_443_p3;
wire   [4:0] imm_1_cast_fu_922_p4;
wire   [31:0] zext_ln202_fu_931_p1;
wire   [11:0] trunc_ln178_fu_947_p1;
wire   [11:0] addr_fu_951_p2;
wire   [9:0] lshr_ln1_fu_957_p4;
wire   [4:0] tmp_7_fu_988_p3;
wire   [11:0] trunc_ln168_fu_1003_p1;
wire   [11:0] imm_s_fu_995_p3;
wire   [11:0] addr_1_fu_1007_p2;
wire   [9:0] lshr_ln2_fu_1013_p4;
wire   [0:0] grp_fu_475_p2;
wire   [0:0] grp_fu_481_p2;
wire   [0:0] grp_fu_487_p2;
wire   [0:0] grp_fu_493_p2;
wire   [0:0] grp_fu_499_p2;
wire   [0:0] grp_fu_505_p2;
wire   [0:0] and_ln63_fu_1063_p2;
wire   [0:0] and_ln61_fu_1068_p2;
wire   [0:0] and_ln59_fu_1073_p2;
wire   [0:0] and_ln57_fu_1078_p2;
wire   [0:0] and_ln55_fu_1083_p2;
wire   [0:0] and_ln53_fu_1088_p2;
wire   [0:0] and_ln53_1_fu_1093_p2;
wire   [31:0] result_14_fu_1116_p6;
wire   [31:0] result_14_fu_1116_p8;
wire   [31:0] result_14_fu_1116_p10;
wire   [31:0] result_14_fu_1116_p12;
wire   [31:0] result_14_fu_1116_p14;
wire   [31:0] result_14_fu_1116_p17;
wire   [6:0] result_14_fu_1116_p18;
wire  signed [31:0] sext_ln200_fu_1184_p1;
wire   [31:0] result_5_fu_1227_p2;
wire   [31:0] result_5_fu_1227_p6;
wire   [31:0] result_5_fu_1227_p10;
wire   [31:0] result_5_fu_1227_p12;
wire   [31:0] result_5_fu_1227_p15;
wire   [5:0] result_5_fu_1227_p16;
wire   [4:0] shl_ln_fu_1281_p3;
wire   [31:0] zext_ln183_fu_1288_p1;
wire   [31:0] lshr_ln183_fu_1292_p2;
wire  signed [21:0] sext_ln157_fu_1317_p1;
wire  signed [21:0] sext_ln127_fu_1355_p1;
wire  signed [31:0] loaded_1_fu_1401_p2;
wire   [31:0] loaded_1_fu_1401_p7;
wire   [1:0] loaded_1_fu_1401_p8;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
wire    ap_block_pp0_stage2_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_1232;
reg    ap_condition_1238;
reg    ap_condition_1243;
wire  signed [6:0] result_14_fu_1116_p1;
wire   [6:0] result_14_fu_1116_p3;
wire   [6:0] result_14_fu_1116_p5;
wire   [6:0] result_14_fu_1116_p7;
wire   [6:0] result_14_fu_1116_p9;
wire   [6:0] result_14_fu_1116_p11;
wire   [6:0] result_14_fu_1116_p13;
wire   [6:0] result_14_fu_1116_p15;
wire  signed [5:0] result_5_fu_1227_p1;
wire   [5:0] result_5_fu_1227_p3;
wire   [5:0] result_5_fu_1227_p5;
wire   [5:0] result_5_fu_1227_p7;
wire   [5:0] result_5_fu_1227_p9;
wire   [5:0] result_5_fu_1227_p11;
wire   [5:0] result_5_fu_1227_p13;
wire  signed [1:0] loaded_1_fu_1401_p1;
wire   [1:0] loaded_1_fu_1401_p3;
wire   [1:0] loaded_1_fu_1401_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 imm_j_fu_192 = 21'd0;
#0 rd_fu_196 = 5'd0;
#0 insn_int_fu_200 = 32'd0;
#0 opcode_fu_204 = 7'd0;
#0 pc_fu_208 = 22'd0;
#0 state_fu_212 = 32'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) cpu_sparsemux_17_7_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 7'h40 ),
    .din0_WIDTH( 32 ),
    .CASE1( 7'h20 ),
    .din1_WIDTH( 32 ),
    .CASE2( 7'h10 ),
    .din2_WIDTH( 32 ),
    .CASE3( 7'h8 ),
    .din3_WIDTH( 32 ),
    .CASE4( 7'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 7'h2 ),
    .din5_WIDTH( 32 ),
    .CASE6( 7'h1 ),
    .din6_WIDTH( 32 ),
    .CASE7( 7'h0 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 7 ),
    .dout_WIDTH( 32 ))
sparsemux_17_7_32_1_1_U2(
    .din0(result_13_reg_1670),
    .din1(result_12_reg_1665),
    .din2(result_14_fu_1116_p6),
    .din3(result_14_fu_1116_p8),
    .din4(result_14_fu_1116_p10),
    .din5(result_14_fu_1116_p12),
    .din6(result_14_fu_1116_p14),
    .din7(32'd0),
    .def(result_14_fu_1116_p17),
    .sel(result_14_fu_1116_p18),
    .dout(result_14_fu_1116_p19)
);

(* dissolve_hierarchy = "yes" *) cpu_sparsemux_15_6_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 6'h20 ),
    .din0_WIDTH( 32 ),
    .CASE1( 6'h10 ),
    .din1_WIDTH( 32 ),
    .CASE2( 6'h8 ),
    .din2_WIDTH( 32 ),
    .CASE3( 6'h4 ),
    .din3_WIDTH( 32 ),
    .CASE4( 6'h2 ),
    .din4_WIDTH( 32 ),
    .CASE5( 6'h1 ),
    .din5_WIDTH( 32 ),
    .CASE6( 6'h0 ),
    .din6_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
sparsemux_15_6_32_1_1_U3(
    .din0(result_5_fu_1227_p2),
    .din1(result_1_reg_1685),
    .din2(result_5_fu_1227_p6),
    .din3(result_3_reg_1690),
    .din4(result_5_fu_1227_p10),
    .din5(result_5_fu_1227_p12),
    .din6(32'd0),
    .def(result_5_fu_1227_p15),
    .sel(result_5_fu_1227_p16),
    .dout(result_5_fu_1227_p17)
);

(* dissolve_hierarchy = "yes" *) cpu_sparsemux_7_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_7_2_32_1_1_U4(
    .din0(loaded_1_fu_1401_p2),
    .din1(word_reg_1715),
    .din2(32'd0),
    .def(loaded_1_fu_1401_p7),
    .sel(loaded_1_fu_1401_p8),
    .dout(loaded_1_fu_1401_p9)
);

cpu_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        insn_int_fu_200 <= 32'd0;
    end else if ((~(state_load_reg_1544 == 32'd1) & ~(state_load_reg_1544 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (icmp_ln101_reg_1540 == 1'd1))) begin
        insn_int_fu_200 <= mem_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        opcode_fu_204 <= 7'd0;
    end else if (((icmp_ln101_fu_573_p2 == 1'd1) & (state_load_load_fu_579_p1 == 32'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        opcode_fu_204 <= opcode_2_fu_600_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_pred381_state4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        opcode_fu_204 <= 7'd111;
    end else if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (((((~(funct3_reg_1595 == 3'd0) & ~(funct3_reg_1595 == 3'd1) & ~(funct3_reg_1595 == 3'd4) & ~(funct3_reg_1595 == 3'd5) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1)) | (~(funct3_reg_1595 == 3'd0) & ~(funct3_reg_1595 == 3'd1) & ~(funct3_reg_1595 == 3'd4) & (grp_fu_511_p2 == 1'd1) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1))) | ((grp_fu_511_p2 == 1'd0) & (funct3_reg_1595 == 3'd4) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1))) | ((grp_fu_517_p2 == 1'd1) & (funct3_reg_1595 == 3'd1) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1))) | ((grp_fu_517_p2 == 1'd0) & (funct3_reg_1595 == 3'd0) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1)))) | ((ap_enable_reg_pp0_iter0_reg 
    == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (((((grp_fu_511_p2 == 1'd1) & (funct3_reg_1595 == 3'd4) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1)) | ((grp_fu_511_p2 == 1'd0) & (funct3_reg_1595 == 3'd5) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1))) | ((grp_fu_517_p2 == 1'd0) & (funct3_reg_1595 == 3'd1) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1))) | ((grp_fu_517_p2 == 1'd1) & (funct3_reg_1595 == 3'd0) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1)))))) begin
        opcode_fu_204 <= 7'd99;
    end else if (((ap_predicate_pred346_state4 == 1'b1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        opcode_fu_204 <= 7'd35;
    end else if (((ap_predicate_pred128_state4 == 1'b1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        opcode_fu_204 <= 7'd19;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (ap_predicate_pred124_state4 == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        opcode_fu_204 <= 7'd51;
    end else if (((ap_predicate_pred341_state5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        opcode_fu_204 <= 7'd3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pc_fu_208 <= 22'd0;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_pred381_state4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        pc_fu_208 <= pc_13_fu_1358_p2;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (((((grp_fu_511_p2 == 1'd1) & (funct3_reg_1595 == 3'd4) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1)) | ((grp_fu_511_p2 == 1'd0) & (funct3_reg_1595 == 3'd5) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1))) | ((grp_fu_517_p2 == 1'd0) & (funct3_reg_1595 == 3'd1) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1))) | ((grp_fu_517_p2 == 1'd1) & (funct3_reg_1595 == 3'd0) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1))))) begin
        pc_fu_208 <= pc_14_fu_1320_p2;
    end else if ((((ap_predicate_pred494_state4 == 1'b1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_predicate_pred468_state4 == 1'b1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (ap_predicate_pred124_state4 == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (((((~(funct3_reg_1595 == 3'd0) & ~(funct3_reg_1595 == 3'd1) & ~(funct3_reg_1595 == 3'd4) & ~(funct3_reg_1595 == 3'd5) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1)) | (~(funct3_reg_1595 == 3'd0) & ~(funct3_reg_1595 == 3'd1) & ~(funct3_reg_1595 == 3'd4) & (grp_fu_511_p2 == 1'd1) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1))) | ((grp_fu_511_p2 == 1'd0) 
    & (funct3_reg_1595 == 3'd4) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1))) | ((grp_fu_517_p2 == 1'd1) & (funct3_reg_1595 == 3'd1) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1))) | ((grp_fu_517_p2 == 1'd0) & (funct3_reg_1595 == 3'd0) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1)))) | ((ap_predicate_pred346_state4 == 1'b1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_predicate_pred128_state4 == 1'b1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        pc_fu_208 <= grp_fu_457_p2;
    end else if (((ap_predicate_pred341_state5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pc_fu_208 <= pc_16_fu_1425_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rd_fu_196 <= 5'd0;
    end else if (((icmp_ln101_fu_573_p2 == 1'd1) & (state_load_load_fu_579_p1 == 32'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        rd_fu_196 <= {{insn_int_fu_200[11:7]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (opcode_1_reg_1528 == 7'd19) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1))) begin
        reg_466 <= reg_file_q0;
    end else if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (funct3_reg_1595 == 3'd0) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (funct3_reg_1595 == 3'd1) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (funct3_reg_1595 == 3'd4) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (funct3_reg_1595 == 3'd5) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) 
    & (1'b1 == ap_CS_fsm_pp0_stage2) & (opcode_1_reg_1528 == 7'd51) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1)))) begin
        reg_466 <= reg_file_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(state_load_load_fu_579_p1 == 32'd2) & ~(state_load_load_fu_579_p1 == 32'd1) & (icmp_ln101_fu_573_p2 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
                state_fu_212[0] <= 1'b1;
        state_fu_212[1] <= 1'b0;
    end else if (((icmp_ln101_fu_573_p2 == 1'd1) & (state_load_load_fu_579_p1 == 32'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
                state_fu_212[0] <= 1'b0;
        state_fu_212[1] <= 1'b1;
    end else if ((((ap_predicate_pred494_state4 == 1'b1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_predicate_pred468_state4 == 1'b1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (ap_predicate_pred124_state4 == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (((((~(funct3_reg_1595 == 3'd0) & ~(funct3_reg_1595 == 3'd1) & ~(funct3_reg_1595 == 3'd4) & ~(funct3_reg_1595 == 3'd5) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1)) | (~(funct3_reg_1595 == 3'd0) & ~(funct3_reg_1595 == 3'd1) & ~(funct3_reg_1595 == 3'd4) & (grp_fu_511_p2 == 1'd1) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1))) | ((grp_fu_511_p2 == 1'd0) 
    & (funct3_reg_1595 == 3'd4) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1))) | ((grp_fu_517_p2 == 1'd1) & (funct3_reg_1595 == 3'd1) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1))) | ((grp_fu_517_p2 == 1'd0) & (funct3_reg_1595 == 3'd0) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1)))) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (((((grp_fu_511_p2 == 1'd1) & (funct3_reg_1595 == 3'd4) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1)) | ((grp_fu_511_p2 == 1'd0) & (funct3_reg_1595 == 3'd5) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1))) | ((grp_fu_517_p2 == 1'd0) & (funct3_reg_1595 == 3'd1) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1))) | ((grp_fu_517_p2 == 
    1'd1) & (funct3_reg_1595 == 3'd0) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1)))) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_pred381_state4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_predicate_pred346_state4 == 1'b1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_predicate_pred128_state4 == 1'b1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_predicate_pred341_state5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
                state_fu_212[0] <= 1'b0;
        state_fu_212[1] <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_predicate_pred124_state4 <= ((opcode_1_reg_1528 == 7'd51) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1));
        ap_predicate_pred128_state4 <= ((opcode_1_reg_1528 == 7'd19) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1));
        ap_predicate_pred140_state4 <= ((funct3_reg_1595 == 3'd5) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1));
        ap_predicate_pred145_state4 <= ((funct3_reg_1595 == 3'd4) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1));
        ap_predicate_pred150_state4 <= ((funct3_reg_1595 == 3'd1) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1));
        ap_predicate_pred155_state4 <= ((funct3_reg_1595 == 3'd0) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1));
        ap_predicate_pred346_state4 <= ((opcode_1_reg_1528 == 7'd35) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1));
        ap_predicate_pred357_state4 <= ((icmp_ln125_reg_1548 == 1'd0) & (opcode_1_reg_1528 == 7'd51) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1));
        ap_predicate_pred363_state4 <= ((icmp_ln125_reg_1548 == 1'd0) & (opcode_1_reg_1528 == 7'd19) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1));
        ap_predicate_pred381_state4 <= ((opcode_1_reg_1528 == 7'd111) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1));
        ap_predicate_pred468_state4 <= (((opcode_1_reg_1528 == 7'd55) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1)) | ((opcode_1_reg_1528 == 7'd23) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1)));
        ap_predicate_pred494_state4 <= (~(opcode_1_reg_1528 == 7'd115) & ~(opcode_1_reg_1528 == 7'd55) & ~(opcode_1_reg_1528 == 7'd111) & ~(opcode_1_reg_1528 == 7'd35) & ~(opcode_1_reg_1528 == 7'd3) & ~(opcode_1_reg_1528 == 7'd23) & ~(opcode_1_reg_1528 == 7'd99) & ~(opcode_1_reg_1528 == 7'd19) & ~(opcode_1_reg_1528 == 7'd51) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1));
        icmp_ln180_1_reg_1710 <= icmp_ln180_1_fu_982_p2;
        icmp_ln180_reg_1705 <= icmp_ln180_fu_976_p2;
        icmp_ln53_reg_1675 <= icmp_ln53_fu_912_p2;
        icmp_ln55_reg_1655 <= icmp_ln55_fu_894_p2;
        result_12_reg_1665 <= result_12_fu_900_p2;
        result_13_reg_1670 <= result_13_fu_906_p2;
        result_1_reg_1685 <= result_1_fu_935_p2;
        result_3_reg_1690 <= result_3_fu_941_p2;
        trunc_ln183_reg_1700 <= trunc_ln183_fu_972_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_predicate_pred341_state5 <= ((opcode_1_reg_1528 == 7'd3) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1));
        ap_predicate_pred374_state5 <= ((icmp_ln125_reg_1548 == 1'd0) & (opcode_1_reg_1528 == 7'd3) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1));
        byte_reg_1720 <= byte_fu_1298_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        funct3_reg_1595 <= {{insn_int_fu_200[14:12]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        icmp_ln101_reg_1540 <= icmp_ln101_fu_573_p2;
        icmp_ln125_reg_1548 <= icmp_ln125_fu_586_p2;
        icmp_ln164_reg_1581 <= icmp_ln164_fu_707_p2;
        icmp_ln222_reg_1562 <= icmp_ln222_fu_680_p2;
        imm_b_reg_1599[4 : 1] <= imm_b_fu_749_p6[4 : 1];
imm_b_reg_1599[12 : 6] <= imm_b_fu_749_p6[12 : 6];
        imm_j_2_reg_1644 <= imm_j_2_fu_852_p2;
        insn_reg_1519 <= insn_int_fu_200;
        opcode_1_reg_1528 <= opcode_fu_204;
        pc_9_reg_1532 <= pc_fu_208;
        rd_1_reg_1511 <= rd_fu_196;
        result_16_reg_1566 <= result_16_fu_686_p2;
        state_load_reg_1544[1 : 0] <= state_fu_212[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        imm_1_reg_1680 <= {{insn_reg_1519[31:20]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_pred381_state4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        imm_j_fu_192 <= imm_j_2_reg_1644;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (opcode_1_reg_1528 == 7'd19) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (opcode_1_reg_1528 == 7'd51) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1)))) begin
        reg_462 <= {{insn_reg_1519[14:12]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (funct3_reg_1595 == 3'd0) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (funct3_reg_1595 == 3'd1) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (funct3_reg_1595 == 3'd4) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (funct3_reg_1595 == 3'd5) & (opcode_1_reg_1528 == 7'd99) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) 
    & (1'b1 == ap_CS_fsm_pp0_stage2) & (opcode_1_reg_1528 == 7'd51) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1)))) begin
        reg_471 <= reg_file_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        word_reg_1715 <= mem_q0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1) & ((icmp_ln101_fu_573_p2 == 1'd0) | ((opcode_1_load_fu_557_p1 == 7'd115) & (state_load_load_fu_579_p1 == 32'd2))))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0_reg == 1'b1)) begin
        if ((1'b1 == ap_condition_1238)) begin
            mem_address0_local = zext_ln169_1_fu_1023_p1;
        end else if ((1'b1 == ap_condition_1232)) begin
            mem_address0_local = zext_ln182_fu_967_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            mem_address0_local = zext_ln105_fu_884_p1;
        end else begin
            mem_address0_local = 'bx;
        end
    end else begin
        mem_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (icmp_ln164_reg_1581 == 1'd1) & (opcode_1_reg_1528 == 7'd35) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (opcode_1_reg_1528 == 7'd3) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1)))) begin
        mem_ce0_local = 1'b1;
    end else begin
        mem_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (icmp_ln164_reg_1581 == 1'd1) & (opcode_1_reg_1528 == 7'd35) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1))) begin
        mem_we0_local = 1'b1;
    end else begin
        mem_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        reg_file_address0_local = zext_ln189_fu_1421_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (ap_predicate_pred363_state4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        reg_file_address0_local = zext_ln212_fu_1262_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (ap_predicate_pred357_state4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        reg_file_address0_local = zext_ln242_fu_1155_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        reg_file_address0_local = zext_ln228_fu_918_p1;
    end else if (((icmp_ln101_fu_573_p2 == 1'd1) & (opcode_1_load_fu_557_p1 == 7'd111) & (state_load_load_fu_579_p1 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln125_fu_586_p2 == 1'd0))) begin
        reg_file_address0_local = zext_ln126_fu_869_p1;
    end else if (((icmp_ln101_fu_573_p2 == 1'd1) & (opcode_1_load_fu_557_p1 == 7'd99) & (state_load_load_fu_579_p1 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (grp_fu_429_p3 == 3'd0))) begin
        reg_file_address0_local = zext_ln141_1_fu_798_p1;
    end else if (((icmp_ln101_fu_573_p2 == 1'd1) & (opcode_1_load_fu_557_p1 == 7'd99) & (state_load_load_fu_579_p1 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (grp_fu_429_p3 == 3'd1))) begin
        reg_file_address0_local = zext_ln145_1_fu_788_p1;
    end else if (((icmp_ln101_fu_573_p2 == 1'd1) & (opcode_1_load_fu_557_p1 == 7'd99) & (state_load_load_fu_579_p1 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (grp_fu_429_p3 == 3'd4))) begin
        reg_file_address0_local = zext_ln149_1_fu_778_p1;
    end else if (((icmp_ln101_fu_573_p2 == 1'd1) & (opcode_1_load_fu_557_p1 == 7'd99) & (state_load_load_fu_579_p1 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (grp_fu_429_p3 == 3'd5))) begin
        reg_file_address0_local = zext_ln153_1_fu_768_p1;
    end else if (((icmp_ln101_fu_573_p2 == 1'd1) & (opcode_1_load_fu_557_p1 == 7'd35) & (state_load_load_fu_579_p1 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln164_fu_707_p2 == 1'd1))) begin
        reg_file_address0_local = zext_ln169_fu_718_p1;
    end else if (((icmp_ln101_fu_573_p2 == 1'd1) & (opcode_1_load_fu_557_p1 == 7'd3) & (state_load_load_fu_579_p1 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        reg_file_address0_local = zext_ln178_fu_702_p1;
    end else if (((icmp_ln101_fu_573_p2 == 1'd1) & (opcode_1_load_fu_557_p1 == 7'd19) & (state_load_load_fu_579_p1 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        reg_file_address0_local = zext_ln197_fu_697_p1;
    end else if (((icmp_ln101_fu_573_p2 == 1'd1) & (opcode_1_load_fu_557_p1 == 7'd55) & (state_load_load_fu_579_p1 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln222_fu_680_p2 == 1'd1))) begin
        reg_file_address0_local = zext_ln223_fu_692_p1;
    end else if (((icmp_ln101_fu_573_p2 == 1'd1) & (opcode_1_load_fu_557_p1 == 7'd51) & (state_load_load_fu_579_p1 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        reg_file_address0_local = zext_ln239_fu_632_p1;
    end else begin
        reg_file_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1243)) begin
        if (((opcode_1_load_fu_557_p1 == 7'd99) & (grp_fu_429_p3 == 3'd0))) begin
            reg_file_address1_local = zext_ln141_fu_793_p1;
        end else if (((opcode_1_load_fu_557_p1 == 7'd99) & (grp_fu_429_p3 == 3'd1))) begin
            reg_file_address1_local = zext_ln145_fu_783_p1;
        end else if (((opcode_1_load_fu_557_p1 == 7'd99) & (grp_fu_429_p3 == 3'd4))) begin
            reg_file_address1_local = zext_ln149_fu_773_p1;
        end else if (((opcode_1_load_fu_557_p1 == 7'd99) & (grp_fu_429_p3 == 3'd5))) begin
            reg_file_address1_local = zext_ln153_fu_763_p1;
        end else if (((opcode_1_load_fu_557_p1 == 7'd35) & (icmp_ln164_fu_707_p2 == 1'd1))) begin
            reg_file_address1_local = zext_ln168_fu_713_p1;
        end else if ((opcode_1_load_fu_557_p1 == 7'd51)) begin
            reg_file_address1_local = zext_ln238_fu_627_p1;
        end else begin
            reg_file_address1_local = 'bx;
        end
    end else begin
        reg_file_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_pred363_state4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_pred357_state4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln101_fu_573_p2 == 1'd1) & (opcode_1_load_fu_557_p1 == 7'd111) & (state_load_load_fu_579_p1 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln125_fu_586_p2 == 1'd0)) | ((icmp_ln101_fu_573_p2 == 1'd1) & (opcode_1_load_fu_557_p1 == 7'd99) & (state_load_load_fu_579_p1 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (grp_fu_429_p3 == 3'd0)) 
    | ((icmp_ln101_fu_573_p2 == 1'd1) & (opcode_1_load_fu_557_p1 == 7'd99) & (state_load_load_fu_579_p1 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (grp_fu_429_p3 == 3'd1)) | ((icmp_ln101_fu_573_p2 == 1'd1) & (opcode_1_load_fu_557_p1 == 7'd99) & (state_load_load_fu_579_p1 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (grp_fu_429_p3 == 3'd4)) | ((icmp_ln101_fu_573_p2 == 1'd1) & (opcode_1_load_fu_557_p1 == 7'd99) & (state_load_load_fu_579_p1 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (grp_fu_429_p3 == 3'd5)) | ((icmp_ln101_fu_573_p2 == 1'd1) & (opcode_1_load_fu_557_p1 == 7'd35) & (state_load_load_fu_579_p1 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln164_fu_707_p2 == 1'd1)) | ((icmp_ln101_fu_573_p2 == 
    1'd1) & (opcode_1_load_fu_557_p1 == 7'd3) & (state_load_load_fu_579_p1 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((icmp_ln101_fu_573_p2 == 1'd1) & (opcode_1_load_fu_557_p1 == 7'd19) & (state_load_load_fu_579_p1 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((icmp_ln101_fu_573_p2 == 1'd1) & (opcode_1_load_fu_557_p1 == 7'd55) & (state_load_load_fu_579_p1 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln222_fu_680_p2 == 1'd1)) | ((icmp_ln101_fu_573_p2 == 1'd1) & (opcode_1_load_fu_557_p1 == 7'd51) & (state_load_load_fu_579_p1 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        reg_file_ce0_local = 1'b1;
    end else begin
        reg_file_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln101_fu_573_p2 == 1'd1) & (opcode_1_load_fu_557_p1 == 7'd99) & (state_load_load_fu_579_p1 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (grp_fu_429_p3 == 3'd0)) | ((icmp_ln101_fu_573_p2 == 1'd1) & (opcode_1_load_fu_557_p1 == 7'd99) & (state_load_load_fu_579_p1 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (grp_fu_429_p3 == 3'd1)) | ((icmp_ln101_fu_573_p2 == 1'd1) & (opcode_1_load_fu_557_p1 == 7'd99) & (state_load_load_fu_579_p1 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (grp_fu_429_p3 == 3'd4)) | ((icmp_ln101_fu_573_p2 == 1'd1) & (opcode_1_load_fu_557_p1 == 7'd99) & (state_load_load_fu_579_p1 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (grp_fu_429_p3 == 3'd5)) | ((icmp_ln101_fu_573_p2 == 1'd1) 
    & (opcode_1_load_fu_557_p1 == 7'd35) & (state_load_load_fu_579_p1 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln164_fu_707_p2 == 1'd1)) | ((icmp_ln101_fu_573_p2 == 1'd1) & (opcode_1_load_fu_557_p1 == 7'd51) & (state_load_load_fu_579_p1 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        reg_file_ce1_local = 1'b1;
    end else begin
        reg_file_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        reg_file_d0_local = loaded_1_fu_1401_p9;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (ap_predicate_pred363_state4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        reg_file_d0_local = result_5_fu_1227_p17;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (ap_predicate_pred357_state4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        reg_file_d0_local = result_14_fu_1116_p19;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        reg_file_d0_local = result_16_reg_1566;
    end else if (((icmp_ln101_fu_573_p2 == 1'd1) & (opcode_1_load_fu_557_p1 == 7'd111) & (state_load_load_fu_579_p1 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln125_fu_586_p2 == 1'd0))) begin
        reg_file_d0_local = zext_ln126_1_fu_864_p1;
    end else if (((icmp_ln101_fu_573_p2 == 1'd1) & (opcode_1_load_fu_557_p1 == 7'd55) & (state_load_load_fu_579_p1 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln222_fu_680_p2 == 1'd1))) begin
        reg_file_d0_local = result_15_fu_665_p3;
    end else begin
        reg_file_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_pred363_state4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_pred357_state4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (icmp_ln222_reg_1562 == 1'd1) & (opcode_1_reg_1528 == 7'd23) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_pred374_state5 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln101_fu_573_p2 == 1'd1) & (opcode_1_load_fu_557_p1 == 7'd111) & (state_load_load_fu_579_p1 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln125_fu_586_p2 == 1'd0)) | ((icmp_ln101_fu_573_p2 == 1'd1) & (opcode_1_load_fu_557_p1 == 7'd55) & (state_load_load_fu_579_p1 
    == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln222_fu_680_p2 == 1'd1)))) begin
        reg_file_we0_local = 1'b1;
    end else begin
        reg_file_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln126_fu_858_p2 = (zext_ln119_fu_596_p1 + 8'd4);

assign addr_1_fu_1007_p2 = (trunc_ln168_fu_1003_p1 + imm_s_fu_995_p3);

assign addr_fu_951_p2 = (trunc_ln178_fu_947_p1 + grp_fu_450_p3);

assign and_ln53_1_fu_1093_p2 = (icmp_ln55_reg_1655 & grp_fu_505_p2);

assign and_ln53_fu_1088_p2 = (icmp_ln53_reg_1675 & grp_fu_505_p2);

assign and_ln55_fu_1083_p2 = (icmp_ln55_reg_1655 & grp_fu_499_p2);

assign and_ln57_fu_1078_p2 = (icmp_ln55_reg_1655 & grp_fu_493_p2);

assign and_ln59_fu_1073_p2 = (icmp_ln55_reg_1655 & grp_fu_487_p2);

assign and_ln61_fu_1068_p2 = (icmp_ln55_reg_1655 & grp_fu_481_p2);

assign and_ln63_fu_1063_p2 = (icmp_ln55_reg_1655 & grp_fu_475_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1232 = ((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (opcode_1_reg_1528 == 7'd3) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1));
end

always @ (*) begin
    ap_condition_1238 = ((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (icmp_ln164_reg_1581 == 1'd1) & (opcode_1_reg_1528 == 7'd35) & (state_load_reg_1544 == 32'd2) & (icmp_ln101_reg_1540 == 1'd1));
end

always @ (*) begin
    ap_condition_1243 = ((icmp_ln101_fu_573_p2 == 1'd1) & (state_load_load_fu_579_p1 == 32'd2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign byte_fu_1298_p1 = lshr_ln183_fu_1292_p2[7:0];

assign grp_fu_415_p3 = {{insn_int_fu_200[19:15]}};

assign grp_fu_422_p3 = {{insn_int_fu_200[24:20]}};

assign grp_fu_429_p3 = {{insn_int_fu_200[14:12]}};

assign grp_fu_436_p3 = {{insn_reg_1519[14:12]}};

assign grp_fu_443_p3 = {{insn_reg_1519[31:25]}};

assign grp_fu_450_p3 = {{insn_reg_1519[31:20]}};

assign grp_fu_457_p2 = (pc_9_reg_1532 + 22'd4);

assign grp_fu_475_p2 = ((reg_462 == 3'd5) ? 1'b1 : 1'b0);

assign grp_fu_481_p2 = ((reg_462 == 3'd1) ? 1'b1 : 1'b0);

assign grp_fu_487_p2 = ((reg_462 == 3'd7) ? 1'b1 : 1'b0);

assign grp_fu_493_p2 = ((reg_462 == 3'd6) ? 1'b1 : 1'b0);

assign grp_fu_499_p2 = ((reg_462 == 3'd4) ? 1'b1 : 1'b0);

assign grp_fu_505_p2 = ((reg_462 == 3'd0) ? 1'b1 : 1'b0);

assign grp_fu_511_p2 = (($signed(reg_466) < $signed(reg_471)) ? 1'b1 : 1'b0);

assign grp_fu_517_p2 = ((reg_466 == reg_471) ? 1'b1 : 1'b0);

assign icmp_ln101_fu_573_p2 = ((tmp_2_fu_563_p4 == 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln125_fu_586_p2 = ((rd_fu_196 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln164_fu_707_p2 = ((grp_fu_429_p3 == 3'd2) ? 1'b1 : 1'b0);

assign icmp_ln180_1_fu_982_p2 = ((grp_fu_436_p3 == 3'd2) ? 1'b1 : 1'b0);

assign icmp_ln180_fu_976_p2 = ((grp_fu_436_p3 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln222_fu_680_p2 = ((rd_fu_196 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln53_fu_912_p2 = ((grp_fu_443_p3 == 7'd32) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_894_p2 = ((grp_fu_443_p3 == 7'd0) ? 1'b1 : 1'b0);

assign imm_1_cast_fu_922_p4 = {{insn_reg_1519[24:20]}};

assign imm_b_fu_749_p6 = {{{{{tmp_9_fu_731_p3}, {tmp_1_fu_739_p4}}, {1'd0}}, {tmp_3_fu_723_p3}}, {1'd0}};

assign imm_j_1_fu_840_p5 = {{imm_j_fu_192[20:20]}, {tmp_6_fu_830_p4}, {imm_j_fu_192[0:0]}};

assign imm_j_2_fu_852_p2 = imm_j_1_fu_840_p5 << 21'd1;

assign imm_s_fu_995_p3 = {{grp_fu_443_p3}, {tmp_7_fu_988_p3}};

assign loaded_1_fu_1401_p2 = $signed(byte_reg_1720);

assign loaded_1_fu_1401_p7 = 'bx;

assign loaded_1_fu_1401_p8 = {{icmp_ln180_reg_1705}, {icmp_ln180_1_reg_1710}};

assign lower_fu_637_p3 = {{rd_fu_196}, {opcode_fu_204}};

assign lshr_ln183_fu_1292_p2 = mem_q0 >> zext_ln183_fu_1288_p1;

assign lshr_ln1_fu_957_p4 = {{addr_fu_951_p2[11:2]}};

assign lshr_ln2_fu_1013_p4 = {{addr_1_fu_1007_p2[11:2]}};

assign lshr_ln_fu_874_p4 = {{pc_fu_208[6:2]}};

assign mem_address0 = mem_address0_local;

assign mem_ce0 = mem_ce0_local;

assign mem_d0 = reg_file_q0;

assign mem_we0 = mem_we0_local;

assign opcode_1_load_fu_557_p1 = opcode_fu_204;

assign opcode_2_fu_600_p1 = insn_int_fu_200[6:0];

assign pc_13_fu_1358_p2 = ($signed(pc_9_reg_1532) + $signed(sext_ln127_fu_1355_p1));

assign pc_14_fu_1320_p2 = ($signed(pc_9_reg_1532) + $signed(sext_ln157_fu_1317_p1));

assign pc_16_fu_1425_p2 = (pc_9_reg_1532 + 22'd4);

assign reg_file_address0 = reg_file_address0_local;

assign reg_file_address1 = reg_file_address1_local;

assign reg_file_ce0 = reg_file_ce0_local;

assign reg_file_ce1 = reg_file_ce1_local;

assign reg_file_d0 = reg_file_d0_local;

assign reg_file_we0 = reg_file_we0_local;

assign result_12_fu_900_p2 = reg_file_q1 << reg_file_q0;

assign result_13_fu_906_p2 = reg_file_q1 >> reg_file_q0;

assign result_14_fu_1116_p10 = (reg_471 ^ reg_466);

assign result_14_fu_1116_p12 = (reg_466 - reg_471);

assign result_14_fu_1116_p14 = (reg_471 + reg_466);

assign result_14_fu_1116_p17 = 'bx;

assign result_14_fu_1116_p18 = {{{{{{{and_ln63_fu_1063_p2}, {and_ln61_fu_1068_p2}}, {and_ln59_fu_1073_p2}}, {and_ln57_fu_1078_p2}}, {and_ln55_fu_1083_p2}}, {and_ln53_fu_1088_p2}}, {and_ln53_1_fu_1093_p2}};

assign result_14_fu_1116_p6 = (reg_471 & reg_466);

assign result_14_fu_1116_p8 = (reg_471 | reg_466);

assign result_15_fu_665_p3 = {{tmp_s_fu_655_p4}, {12'd0}};

assign result_16_fu_686_p2 = (result_15_fu_665_p3 + zext_ln119_1_fu_582_p1);

assign result_1_fu_935_p2 = reg_file_q0 << zext_ln202_fu_931_p1;

assign result_3_fu_941_p2 = reg_file_q0 >> zext_ln202_fu_931_p1;

assign result_5_fu_1227_p10 = (sext_ln200_fu_1184_p1 | reg_466);

assign result_5_fu_1227_p12 = (sext_ln200_fu_1184_p1 & reg_466);

assign result_5_fu_1227_p15 = 'bx;

assign result_5_fu_1227_p16 = {{{{{{grp_fu_505_p2}, {grp_fu_481_p2}}, {grp_fu_499_p2}}, {grp_fu_475_p2}}, {grp_fu_493_p2}}, {grp_fu_487_p2}};

assign result_5_fu_1227_p2 = ($signed(reg_466) + $signed(sext_ln200_fu_1184_p1));

assign result_5_fu_1227_p6 = (sext_ln200_fu_1184_p1 ^ reg_466);

assign sext_ln127_fu_1355_p1 = imm_j_2_reg_1644;

assign sext_ln157_fu_1317_p1 = $signed(imm_b_reg_1599);

assign sext_ln200_fu_1184_p1 = $signed(imm_1_reg_1680);

assign shl_ln_fu_1281_p3 = {{trunc_ln183_reg_1700}, {3'd0}};

assign state_load_load_fu_579_p1 = state_fu_212;

assign sub_ln219_fu_649_p2 = (insn_int_fu_200 - zext_ln218_fu_645_p1);

assign tmp_1_fu_739_p4 = {{insn_int_fu_200[30:25]}};

assign tmp_2_fu_563_p4 = {{pc_fu_208[21:7]}};

assign tmp_3_fu_723_p3 = {{insn_int_fu_200[11:8]}};

assign tmp_4_fu_822_p3 = {{insn_int_fu_200[30:21]}};

assign tmp_6_fu_830_p4 = {{{tmp_fu_806_p3}, {tmp_8_fu_814_p3}}, {tmp_4_fu_822_p3}};

assign tmp_7_fu_988_p3 = {{insn_reg_1519[11:7]}};

assign tmp_8_fu_814_p3 = insn_int_fu_200[32'd20];

assign tmp_9_fu_731_p3 = insn_int_fu_200[32'd7];

assign tmp_fu_806_p3 = {{insn_int_fu_200[19:12]}};

assign tmp_s_fu_655_p4 = {{sub_ln219_fu_649_p2[31:12]}};

assign trunc_ln119_fu_592_p1 = pc_fu_208[6:0];

assign trunc_ln168_fu_1003_p1 = reg_file_q1[11:0];

assign trunc_ln178_fu_947_p1 = reg_file_q0[11:0];

assign trunc_ln183_fu_972_p1 = addr_fu_951_p2[1:0];

assign zext_ln105_fu_884_p1 = lshr_ln_fu_874_p4;

assign zext_ln119_1_fu_582_p1 = pc_fu_208;

assign zext_ln119_fu_596_p1 = trunc_ln119_fu_592_p1;

assign zext_ln126_1_fu_864_p1 = add_ln126_fu_858_p2;

assign zext_ln126_fu_869_p1 = rd_fu_196;

assign zext_ln141_1_fu_798_p1 = grp_fu_422_p3;

assign zext_ln141_fu_793_p1 = grp_fu_415_p3;

assign zext_ln145_1_fu_788_p1 = grp_fu_422_p3;

assign zext_ln145_fu_783_p1 = grp_fu_415_p3;

assign zext_ln149_1_fu_778_p1 = grp_fu_422_p3;

assign zext_ln149_fu_773_p1 = grp_fu_415_p3;

assign zext_ln153_1_fu_768_p1 = grp_fu_422_p3;

assign zext_ln153_fu_763_p1 = grp_fu_415_p3;

assign zext_ln168_fu_713_p1 = grp_fu_415_p3;

assign zext_ln169_1_fu_1023_p1 = lshr_ln2_fu_1013_p4;

assign zext_ln169_fu_718_p1 = grp_fu_422_p3;

assign zext_ln178_fu_702_p1 = grp_fu_415_p3;

assign zext_ln182_fu_967_p1 = lshr_ln1_fu_957_p4;

assign zext_ln183_fu_1288_p1 = shl_ln_fu_1281_p3;

assign zext_ln189_fu_1421_p1 = rd_1_reg_1511;

assign zext_ln197_fu_697_p1 = grp_fu_415_p3;

assign zext_ln202_fu_931_p1 = imm_1_cast_fu_922_p4;

assign zext_ln212_fu_1262_p1 = rd_1_reg_1511;

assign zext_ln218_fu_645_p1 = lower_fu_637_p3;

assign zext_ln223_fu_692_p1 = rd_fu_196;

assign zext_ln228_fu_918_p1 = rd_1_reg_1511;

assign zext_ln238_fu_627_p1 = grp_fu_415_p3;

assign zext_ln239_fu_632_p1 = grp_fu_422_p3;

assign zext_ln242_fu_1155_p1 = rd_1_reg_1511;

always @ (posedge ap_clk) begin
    state_load_reg_1544[31:2] <= 30'b000000000000000000000000000000;
    imm_b_reg_1599[0] <= 1'b0;
    imm_b_reg_1599[5] <= 1'b0;
    state_fu_212[31:2] <= 30'b000000000000000000000000000000;
end

endmodule //cpu_cpu_Pipeline_VITIS_LOOP_101_2
